services:
  frontend:
    build:
      context: frontend
      target: prod
    ports:
      - 5000:80
    # stdin_open: true
    restart: always
  
  backend:
    build:
      context: backend
      target: prod
    ports:
      - 5001:3000
    restart: always
