services:
  frontend:
    build:
      context: frontend
      target: dev
    ports:
      - 5000:5000
    stdin_open: true
    volumes:
      - ./frontend/src:/app/src
    networks:
      - react-express
    depends_on:
      - backend

  backend:
    build:
      context: backend
      target: dev
    expose:
      - 5000
    networks:
      - react-express
      - express-mongo
    depends_on:
      - mongo

  mongo:
    restart: always
    image: mongo:4.2.0
    expose:
      - 27017
    volumes:
    - mongo_data:/data/db
    networks:
      - express-mongo

networks:
  react-express:
  express-mongo:

volumes:
  mongo_data: