services:
  frontend:
    restart: always
    build:
      context: frontend
      target: prod
    ports:
      - 80:5000
    networks:
      - react-express
    depends_on:
      - backend

  backend:
    restart: always
    build:
      context: backend
      target: prod
    expose:
      - 5000
    networks:
      - react-express
      - express-mongo
    depends_on:
      - mongo

  mongo:
    restart: always
    image: mongo:4.4
    expose:
      - 27017
    volumes:
      - mongo_data:/data/db
    networks:
      - express-mongo

networks:
  react-express:
  express-mongo:

volumes:
  mongo_data: