services:
  frontend:
    build:
      context: frontend
      target: dev
    env_file: ./frontend/.env.dev
    ports:
      - 5000:5000
    stdin_open: true
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - frontend-backend
    depends_on:
      - backend

  backend:
    build:
      context: backend
      target: dev
    env_file: ./backend/.env.dev
    expose:
      - 5000
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - frontend-backend
      - backend-db
    depends_on:
      - mongo

  mongo:
    image: mongo:4.4
    expose:
      - 27017
    volumes:
      - mongo-data:/data/db
    networks:
      - backend-db

networks:
  frontend-backend:
  backend-db:

volumes:
  mongo-data: