services:
  frontend:
    build:
      context: frontend
      target: prod
    ports:
      - 5000:5000
    # stdin_open: true
    # restart: always
    networks:
      - react-express
    depends_on:
      - backend

  backend:
    build:
      context: backend
      target: prod
    expose:
      - 5000
    # restart: always
    networks:
      - react-express

networks:
  react-express: