services:
  frontend:
    build:
      context: frontend
      target: dev
    environment:
      - PORT=5000
      - WATCHPACK_POLLING=true
    ports:
      - 5000:5000
    stdin_open: true
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - react-express
    depends_on:
      - backend

  backend:
    build:
      context: backend
      target: dev
    expose:
      - 5000
    networks:
      - react-express
      - express-mongo
    depends_on:
      - mongo

  mongo:
    # restart: always
    image: mongo:4.4
    expose:
      - 27017
    volumes:
      - mongo_data:/data/db
    networks:
      - express-mongo

networks:
  react-express:
  express-mongo:

volumes:
  mongo_data: