services:
  web1:
    hostname: web1
    build:
      context: ./web
      target: prod
    command: python manage.py runserver 0.0.0.0:5000
    ports:
      - 81:5000

  web2:
    hostname: web2
    build:
      context: ./web
      target: prod
    command: python manage.py runserver 0.0.0.0:5000
    ports:
      - 82:5000

  nginx:
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - web1
      - web2
