services:
  client:
    build:
      context: client
      target: dev
    env_file: ./client/.env.dev
    ports:
      - 5000:5000
    stdin_open: true
    volumes:
      - ./client:/app
      - /app/node_modules
    networks:
      - client-server
    depends_on:
      - server

  server:
    build:
      context: server
      target: dev
    expose:
      - 5000
    volumes:
      - ./server:/app
      - /app/node_modules
    networks:
      - client-server
      - server-db
    # depends_on:
    #   - mongo

  # mongo:
  #   image: mongo:4.4
  #   expose:
  #     - 27017
  #   volumes:
  #     - mongo-data:/data/db
  #   networks:
  #     - server-db

networks:
  client-server:
  server-db:

volumes:
  mongo-data: