services:
  client:
    build:
      context: client
      target: dev
    env_file: ./client/.env.dev
    ports:
      - 5000:5000
    stdin_open: true
    volumes:
      - ./client:/app
      - /app/node_modules
    networks:
      - client-server
    depends_on:
      - server

  server:
    build:
      context: server
      target: dev
    command: python manage.py runserver 0.0.0.0:8000
    env_file: ./server/.env.dev
    ports:
      - 8000:8000
    volumes:
      - ./server:/app
    networks:
      - client-server
      - server-db
    depends_on:
      - db

  db:
    image: postgres:14
    env_file: ./db/.env.dev
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - server-db

networks:
  client-server:
  server-db:

volumes:
  db-data: