services:
  client:
    restart: always
    build:
      context: client
      target: prod
    env_file: ./client/.env.prod
    ports:
      - 5000:5000
    networks:
      - client-server
    depends_on:
      - server

  server:
    restart: always
    build:
      context: server
      target: prod
    command: python manage.py runserver 0.0.0.0:8000 #todo
    env_file: ./server/.env.prod
    ports:
      - 8000:8000
    volumes:
      - ./server:/app
    networks:
      - client-server
      - server-db
    depends_on:
      - db

  db:
    restart: always
    image: postgres:14
    env_file: ./db/.env.prod
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - server-db

networks:
  client-server:
  server-db:

volumes:
  db-data: